import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by scripts/copy-pyodide-assets.mjs (postinstall) - a
    // vendored emscripten build artifact, not source to lint.
    "public/pyodide/**",
    // Playwright's HTML report output (gitignored, but this config
    // replaces eslint-config-next's own ignores wholesale rather than
    // extending them, so this needs restating here too).
    "playwright-report/**",
    "test-results/**",
    "blob-report/**",
  ]),
]);

export default eslintConfig;
